# Generated by Django 3.0.2 on 2020-09-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200924_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
