# Generated by Django 3.0.2 on 2020-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='ordered',
            name='logistics',
            field=models.IntegerField(default=0, verbose_name='total'),
        ),
    ]
