# Generated by Django 3.0.2 on 2020-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201006_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['topping'], 'verbose_name': 'Topping', 'verbose_name_plural': 'Toppings'},
        ),
        migrations.AddField(
            model_name='ordered',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordered',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
