# Generated by Django 3.0.2 on 2020-10-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201012_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='destination',
            field=models.CharField(default='null', max_length=150, verbose_name='destination'),
        ),
    ]
