# Generated by Django 3.0.2 on 2020-10-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_ordered_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='name')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.IntegerField()),
                ('purchaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseIdTopping', to='backend.Ordered', verbose_name='purchase id')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedtopping', to='backend.Topping', verbose_name='topping')),
            ],
            options={
                'verbose_name': 'OrderedTopping',
                'verbose_name_plural': 'OrderedToppings',
                'managed': True,
            },
        ),
    ]
