# Generated by Django 3.1.5 on 2021-05-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_orderedtopping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordered',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
